CC:=gcc

thread_create_test: thread_create_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

terminate_test: terminate_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

thread_detach_test: thread_detach_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

thread_cancel_test: thread_cancel_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

thread_cancel_async_test: thread_cancel_async_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

thread_cancel_disable_test: thread_cancel_disable_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

race_condition_test: race_condition_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

mutex_test: mutex_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@